### PR TITLE
Containerise fetch service

### PR DESCRIPTION
**Pull request by lukekearney**
Puts the fetch service in a docker container and adds basic logging. Assuming the mongo data is being updated correctly, this should be ready to deploy.

Notification service will be added later

### CODE REVIEW

**Comment by KatjaRademacher** [comment]
@aknutas Could see if this is working for you on docker? The code looks fine to me but docker is still messed up on my VM at home and haven't been able to fix it (even with uninstall and reinstall).

Thanks

**Comment by aknutas** [comment]
Hi,
   it should work on Linux and OS X, but sharing drive mounts does not work on certain versions of Windows (which is used for storing the database files outside the instances themselves). I am happy for this to work on POSIX OSes only.

> ERROR: for mongo  Cannot create container for service mongo: b'An error occurred while sharing drive'
> ERROR: Cannot create container for service mongo: b'An error occurred while sharing drive'
> PS C:\Users\aknutas\tmp\transparentwater_backend_new> ls

**Comment by aknutas** [comment]
> Hi,
> it should work on Linux and OS X, but sharing drive mounts does not work on certain versions of Windows (which is used for storing the database files outside the instances themselves). I am happy for this to work on POSIX OSes only.
> 
> > ERROR: for mongo  Cannot create container for service mongo: b'An error occurred while sharing drive'
> > ERROR: Cannot create container for service mongo: b'An error occurred while sharing drive'
> > PS C:\Users\aknutas\tmp\transparentwater_backend_new> ls

Addendum: This error is not caused by our implementation, but the way Docker is implemented on Windows and how Windows works.

**Review by aknutas — APPROVED** [review]
Works fine on POSIX compatible OSes, such as Linux and OS X.

> Hi,
> it should work on Linux and OS X, but sharing drive mounts does not work on certain versions of Windows (which is used for storing the database files outside the instances themselves). I am happy for this to work on POSIX OSes only.
> 
> > ERROR: for mongo  Cannot create container for service mongo: b'An error occurred while sharing drive'
> > ERROR: Cannot create container for service mongo: b'An error occurred while sharing drive'
> > PS C:\Users\aknutas\tmp\transparentwater_backend_new> ls

Addendum: This error is not caused by our implementation, but the way Docker is implemented on Windows and how Windows works.

**Pull request merged**
